worker_processes auto;

events {
    worker_connections 10240;
}

http {
    upstream kgs_backend {
        server kgs:8080;
        # Keep 500 connections alive to backend servers to eliminate TCP handshake overhead
        keepalive 500;
    }

    server {
        listen 80;

        location /key {
            proxy_pass http://kgs_backend/key;
            
            # Required for HTTP keepalive to upstreams
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
